#!/bin/bash
APP_NAME="cd"
APP_DESCRIPTION="Extends builtin cd-command with traverseable history."
APP_DIR=${BASH_SOURCE%/*}
APP_VERSION="0.1"
APP_AUTHOR="rednammoc"
APP_AUTHOR_EMAIL="rednammoc@gmx.de"

# Load bash-utils core.
[ ! -d "$APP_DIR" ] && APP_DIR="$PWD"
BASH_UTILS_DIR="${APP_DIR}/lib/bash-utils/src/utils"
BASH_UTILS_CORE="${BASH_UTILS_DIR}/core_utils.sh"
source "${BASH_UTILS_CORE}" || return 1

# Require utils.
require "list_utils.sh"

# Check dependencies.
depends "cd_history"

if [ "$1" == "-" ] || [ "$1" == "+" ]
then
	cd_history "$1"
else
	local lwd=$(pwd)
	if [ -z "$1" ] ; then builtin cd; else builtin cd "$1"; fi
	local cwd=$(pwd)
	if [ "${lwd}" != "${cwd}" ]
	then
		local history_size=$(cd_history -l | wc -l)
		# When history is empty add the starting directory as well.
		[ ${list_size} -eq 0 ] && cd_history -a "${lwd}"
		# Add current directory to history.
		cd_history -a "${cwd}"
	fi
fi
