#!/bin/bash
APP_NAME="cd_stats"
APP_DESCRIPTION="Statistical analyse of cd-history."
APP_DIR=${BASH_SOURCE%/*}
APP_VERSION="0.1"
APP_AUTHOR="rednammoc"
APP_AUTHOR_EMAIL="rednammoc@gmx.de"

# Load bash-utils core.
[ ! -d "${APP_DIR}" ] && APP_DIR="${PWD}"
BASH_UTILS_DIR="${APP_DIR}/lib/bash-utils/src/utils"
BASH_UTILS_CORE="${BASH_UTILS_DIR}/core_utils.sh"
source "${BASH_UTILS_CORE}" || return 1

# Require utils.
require "list_utils.sh"

function usage
{
	cat <<EOM
Usage: ${APP_NAME} <file> [options]
		
Options:
 -t               show list sorted by number of occurences.
 -c               prefix lines with number of occurences.
 -h, --help       show this help message and exit.
EOM
}

if [ $? -ne 0 ]
then
	usage
fi

while getopts ":tc" options; do
	case "$options" in
	t )
		SHOW_LIST=1
		;;
	c )
		PREFIX_LINES=1
		;;	
	h | help )
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
FILE="${1}"

if [ "${PREFIX_LINES}" ] && ! [ "${SHOW_LIST}" ]
then
	echo "Error: Option -c can not be used alone!"
	exit 1
fi

if [ "${SHOW_LIST}" ]
then
	if ! [ -f "${FILE}" ]
	then
		echo "Error: File '${FILE}' does not exist! Abort."
		exit 1
	fi
	
	OUTPUT=$(sort "${FILE}" | uniq -c | sort -r)
	if ! [ "${PREFIX_LINES}" ]
	then
		OUTPUT=$(echo "${OUTPUT}" | cut -b 1-8 --complement)
	fi
	echo "${OUTPUT}"
fi

